config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "recipes#index"

  get '/users/new',      :controller => 'users', :action => 'new',    :as => 'new_user'
  post '/users',         :controller => 'users', :action => 'create', :as => 'users'

  get '/users',          :controller => 'users', :action => 'index'
  get '/users/:id',      :controller => 'users', :action => 'show',   :as => 'user'

  get '/users/:id/edit', :controller => 'users', :action => 'edit',   :as => 'edit_user'
  patch '/users/:id',    :controller => 'users', :action => 'update'

  delete '/users/:id',   :controller => 'users', :action => 'destroy'

  get '/ingredients/new',      :controller => 'ingredients', :action => 'new',    :as => 'new_ingredient'
  post '/ingredients',         :controller => 'ingredients', :action => 'create', :as => 'ingredients'

  get '/ingredients',          :controller => 'ingredients', :action => 'index'
  get '/ingredients/:id',      :controller => 'ingredients', :action => 'show',   :as => 'ingredient'

  get '/ingredients/:id/edit', :controller => 'ingredients', :action => 'edit',   :as => 'edit_ingredient'
  patch '/ingredients/:id',    :controller => 'ingredients', :action => 'update'

  delete '/ingredients/:id',   :controller => 'ingredients', :action => 'destroy'

  get '/recipe_ingredients/new',      :controller => 'recipe_ingredients', :action => 'new',    :as => 'new_recipe_ingredient'
  post '/recipe_ingredients',         :controller => 'recipe_ingredients', :action => 'create', :as => 'recipe_ingredients'

  get '/recipe_ingredients',          :controller => 'recipe_ingredients', :action => 'index'
  get '/recipe_ingredients/:id',      :controller => 'recipe_ingredients', :action => 'show',   :as => 'recipe_ingredient'

  get '/recipe_ingredients/:id/edit', :controller => 'recipe_ingredients', :action => 'edit',   :as => 'edit_recipe_ingredient'
  patch '/recipe_ingredients/:id',    :controller => 'recipe_ingredients', :action => 'update'

  delete '/recipe_ingredients/:id',   :controller => 'recipe_ingredients', :action => 'destroy'

  get '/recipes/new',      :controller => 'recipes', :action => 'new',    :as => 'new_recipe'
  post '/recipes',         :controller => 'recipes', :action => 'create', :as => 'recipes'

  get '/recipes',          :controller => 'recipes', :action => 'index'
  get '/recipes/:id',      :controller => 'recipes', :action => 'show',   :as => 'recipe'

  get '/recipes/:id/edit', :controller => 'recipes', :action => 'edit',   :as => 'edit_recipe'
  patch '/recipes/:id',    :controller => 'recipes', :action => 'update'

  delete '/recipes/:id',   :controller => 'recipes', :action => 'destroy'

  get '/meals/new',      :controller => 'meals', :action => 'new',    :as => 'new_meal'
  post '/meals',         :controller => 'meals', :action => 'create', :as => 'meals'

  get '/meals',          :controller => 'meals', :action => 'index'
  get '/meals/:id',      :controller => 'meals', :action => 'show',   :as => 'meal'

  get '/meals/:id/edit', :controller => 'meals', :action => 'edit',   :as => 'edit_meal'
  patch '/meals/:id',    :controller => 'meals', :action => 'update'

  delete '/meals/:id',   :controller => 'meals', :action => 'destroy'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to users_url, :notice => "User created successfully."
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes(user_params)

    if @user.save
      redirect_to user_url(@user.id), :notice => "User updated successfully."
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to users_url, :notice => "User deleted."
  end

  def user_params
    params.require(:user).permit(:email, :username, :image_url)
  end
end

app/views/users/_form.html.erb
<%= form_for(@user, html: {class: 'form-horizontal'}) do |f| %>
  <!-- Label and input for email -->
  <div class="form-group">
    <%= f.label :email, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :email, placeholder: 'Email', class: 'form-control' %>
    </div>
  </div>

  <!-- Label and input for username -->
  <div class="form-group">
    <%= f.label :username, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :username, placeholder: 'Username', class: 'form-control' %>
    </div>
  </div>

  <!-- Label and input for image_url -->
  <div class="form-group">
    <%= f.label :image_url, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :image_url, placeholder: 'Image URL', class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: 'btn btn-default' %>
      or
      <a href="/users">Cancel</a>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<!-- Validation failure messages -->

<% if @user.errors.any? %>
  <% @user.errors.full_messages.each do |message| %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= message %>
    </div>
  <% end %>
<% end %>

<!-- Responsive panel example -->

<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Edit User #<%= @user.id %></h3>
      </div>
      <div class="panel-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>


<!-- End responsive panel example -->

app/views/users/index.html.erb
<div class="page-header">
  <h1>
    Users
    <%= link_to new_user_url, :class => "btn btn-lg btn-success" do %>
      <i class="fa fa-plus"></i>
    <% end  %>
  </h1>
</div>

<!-- Responsive, Isotope-based layout example -->

<div class="row">
  <div class="col-xs-12">
    <input type="text" id="quicksearch" placeholder="Search Users (start typing)" class="form-control">
  </div>
</div>

<hr>

<div class="row isotope-container">
<% @users.each do |user| %>
  <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 isotope-item">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">User #<%= user.id %></h3>
      </div>
      <div class="panel-body">
        <dl>
          <dt>Email</dt>
          <dd><%= user.email %></dd>

          <dt>Username</dt>
          <dd><%= user.username %></dd>

          <dt>Image url</dt>
          <dd><%= user.image_url %></dd>

        </dl>
        <div class="btn-group btn-group-justified">
          <%= link_to user_url(user), :class => "btn btn-primary" do %>
            <i class="fa fa-search-plus"></i>
          <% end %>
          <%= link_to edit_user_url(user), :class => "btn btn-warning" do %>
            <i class="fa fa-edit"></i>
          <% end %>
          <%= link_to user_url(user), :method => "delete", :data => { :confirm => "Do you really want to delete this user?" }, :class => "btn btn-danger" do %>
            <i class="fa fa-trash-o"></i>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>
</div>

<!-- JavaScript for Isotope layout and quicksearch -->
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/3.1.8/imagesloaded.pkgd.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.isotope/2.0.0/isotope.pkgd.min.js"></script>
<script>
  $(function() {
    // quick search regex
    var qsRegex;

    // init Isotope
    var $container = $('.isotope-container');

    $container.imagesLoaded(function() {
      $container.isotope({
        itemSelector: '.isotope-item',
        layoutMode: 'masonry',
        filter: function() {
          return qsRegex ? $(this).text().match( qsRegex ) : true;
        }
      })
    });

    // use value of search field to filter
    var $quicksearch = $('#quicksearch').keyup( debounce( function() {
      qsRegex = new RegExp( $quicksearch.val(), 'gi' );
      $container.isotope();
    }, 200 ) );

  });

  // debounce so filtering doesn't happen every millisecond
  function debounce( fn, threshold ) {
    var timeout;
    return function debounced() {
      if ( timeout ) {
        clearTimeout( timeout );
      }
      function delayed() {
        fn();
        timeout = null;
      }
      timeout = setTimeout( delayed, threshold || 100 );
    }
  }
</script>

<!-- End responsive, Isotope-based layout example -->

app/views/users/new.html.erb
<!-- Validation failure messages -->

<% if @user.errors.any? %>
  <% @user.errors.full_messages.each do |message| %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= message %>
    </div>
  <% end %>
<% end %>

<!-- Responsive panel example -->

<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Add User</h3>
      </div>
      <div class="panel-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

<!-- End responsive panel example -->

app/views/users/show.html.erb
<!-- Responsive panel example-->

<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">User #<%= @user.id %></h3>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-md-12">
            <dl class="dl-horizontal">
              <dt>Email</dt>
              <dd><%= @user.email %></dd>

              <dt>Username</dt>
              <dd><%= @user.username %></dd>

              <dt>Image url</dt>
              <dd><%= @user.image_url %></dd>

            </dl>
            <div class="btn-group btn-group-justified">
              <%= link_to users_url, :class => "btn btn-primary" do %>
                <i class="fa fa-chevron-left"></i>
              <% end %>
              <%= link_to edit_user_url(@user.id), :class => "btn btn-warning" do %>
                <i class="fa fa-edit"></i>
              <% end %>
              <%= link_to user_url(@user.id), :method => "delete", :data => { :confirm => "Do you really want to delete this user?" }, :class => "btn btn-danger" do %>
                <i class="fa fa-trash-o"></i>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- End responsive panel example -->