config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "recipes#index"

  get '/users/new',      :controller => 'users', :action => 'new',    :as => 'new_user'
  post '/users',         :controller => 'users', :action => 'create', :as => 'users'

  get '/users',          :controller => 'users', :action => 'index'
  get '/users/:id',      :controller => 'users', :action => 'show',   :as => 'user'

  get '/users/:id/edit', :controller => 'users', :action => 'edit',   :as => 'edit_user'
  patch '/users/:id',    :controller => 'users', :action => 'update'

  delete '/users/:id',   :controller => 'users', :action => 'destroy'

  get '/ingredients/new',      :controller => 'ingredients', :action => 'new',    :as => 'new_ingredient'
  post '/ingredients',         :controller => 'ingredients', :action => 'create', :as => 'ingredients'

  get '/ingredients',          :controller => 'ingredients', :action => 'index'
  get '/ingredients/:id',      :controller => 'ingredients', :action => 'show',   :as => 'ingredient'

  get '/ingredients/:id/edit', :controller => 'ingredients', :action => 'edit',   :as => 'edit_ingredient'
  patch '/ingredients/:id',    :controller => 'ingredients', :action => 'update'

  delete '/ingredients/:id',   :controller => 'ingredients', :action => 'destroy'

  get '/recipe_ingredients/new',      :controller => 'recipe_ingredients', :action => 'new',    :as => 'new_recipe_ingredient'
  post '/recipe_ingredients',         :controller => 'recipe_ingredients', :action => 'create', :as => 'recipe_ingredients'

  get '/recipe_ingredients',          :controller => 'recipe_ingredients', :action => 'index'
  get '/recipe_ingredients/:id',      :controller => 'recipe_ingredients', :action => 'show',   :as => 'recipe_ingredient'

  get '/recipe_ingredients/:id/edit', :controller => 'recipe_ingredients', :action => 'edit',   :as => 'edit_recipe_ingredient'
  patch '/recipe_ingredients/:id',    :controller => 'recipe_ingredients', :action => 'update'

  delete '/recipe_ingredients/:id',   :controller => 'recipe_ingredients', :action => 'destroy'

  get '/recipes/new',      :controller => 'recipes', :action => 'new',    :as => 'new_recipe'
  post '/recipes',         :controller => 'recipes', :action => 'create', :as => 'recipes'

  get '/recipes',          :controller => 'recipes', :action => 'index'
  get '/recipes/:id',      :controller => 'recipes', :action => 'show',   :as => 'recipe'

  get '/recipes/:id/edit', :controller => 'recipes', :action => 'edit',   :as => 'edit_recipe'
  patch '/recipes/:id',    :controller => 'recipes', :action => 'update'

  delete '/recipes/:id',   :controller => 'recipes', :action => 'destroy'

  get '/meals/new',      :controller => 'meals', :action => 'new',    :as => 'new_meal'
  post '/meals',         :controller => 'meals', :action => 'create', :as => 'meals'

  get '/meals',          :controller => 'meals', :action => 'index'
  get '/meals/:id',      :controller => 'meals', :action => 'show',   :as => 'meal'

  get '/meals/:id/edit', :controller => 'meals', :action => 'edit',   :as => 'edit_meal'
  patch '/meals/:id',    :controller => 'meals', :action => 'update'

  delete '/meals/:id',   :controller => 'meals', :action => 'destroy'

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  def recipe_ingredients
    RecipeIngredient.where(ingredient_id: self.id)
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
    @ingredients = Ingredient.all
  end

  def show
    @ingredient = Ingredient.find(params[:id])
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    if @ingredient.save
      redirect_to ingredients_url, :notice => "Ingredient created successfully."
    else
      render 'new'
    end
  end

  def edit
    @ingredient = Ingredient.find(params[:id])
  end

  def update
    @ingredient = Ingredient.find(params[:id])
    @ingredient.update_attributes(ingredient_params)

    if @ingredient.save
      redirect_to ingredient_url(@ingredient.id), :notice => "Ingredient updated successfully."
    else
      render 'edit'
    end
  end

  def destroy
    @ingredient = Ingredient.find(params[:id])

    @ingredient.destroy

    redirect_to ingredients_url, :notice => "Ingredient deleted."
  end

  def ingredient_params
    params.require(:ingredient).permit(:name, :category, :price_per_unit, :unit)
  end
end

app/views/ingredients/_form.html.erb
<%= form_for(@ingredient, html: {class: 'form-horizontal'}) do |f| %>
  <!-- Label and input for name -->
  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, placeholder: 'Name', class: 'form-control' %>
    </div>
  </div>

  <!-- Label and input for category -->
  <div class="form-group">
    <%= f.label :category, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :category, placeholder: 'Category', class: 'form-control' %>
    </div>
  </div>

  <!-- Label and input for price_per_unit -->
  <div class="form-group">
    <%= f.label :price_per_unit, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :price_per_unit, placeholder: 'Price Per Unit', class: 'form-control' %>
    </div>
  </div>

  <!-- Label and input for unit -->
  <div class="form-group">
    <%= f.label :unit, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :unit, placeholder: 'Unit', class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: 'btn btn-default' %>
      or
      <a href="/ingredients">Cancel</a>
    </div>
  </div>
<% end %>

app/views/ingredients/edit.html.erb
<!-- Validation failure messages -->

<% if @ingredient.errors.any? %>
  <% @ingredient.errors.full_messages.each do |message| %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= message %>
    </div>
  <% end %>
<% end %>

<!-- Responsive panel example -->

<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Edit Ingredient #<%= @ingredient.id %></h3>
      </div>
      <div class="panel-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>


<!-- End responsive panel example -->

app/views/ingredients/index.html.erb
<div class="page-header">
  <h1>
    Ingredients
    <%= link_to new_ingredient_url, :class => "btn btn-lg btn-success" do %>
      <i class="fa fa-plus"></i>
    <% end  %>
  </h1>
</div>

<!-- Responsive, Isotope-based layout example -->

<div class="row">
  <div class="col-xs-12">
    <input type="text" id="quicksearch" placeholder="Search Ingredients (start typing)" class="form-control">
  </div>
</div>

<hr>

<div class="row isotope-container">
<% @ingredients.each do |ingredient| %>
  <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 isotope-item">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= ingredient.name %></h3>
      </div>
      <div class="panel-body">
        <dl>
          <dt>Category</dt>
          <dd><%= ingredient.category %></dd>

          <dt>Price per unit</dt>
          <dd><%= ingredient.price_per_unit %></dd>

          <dt>Unit</dt>
          <dd><%= ingredient.unit %></dd>

        </dl>
        <div class="btn-group btn-group-justified">
          <%= link_to ingredient_url(ingredient), :class => "btn btn-primary" do %>
            <i class="fa fa-search-plus"></i>
          <% end %>
          <%= link_to edit_ingredient_url(ingredient), :class => "btn btn-warning" do %>
            <i class="fa fa-edit"></i>
          <% end %>
          <%= link_to ingredient_url(ingredient), :method => "delete", :data => { :confirm => "Do you really want to delete this ingredient?" }, :class => "btn btn-danger" do %>
            <i class="fa fa-trash-o"></i>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>
</div>

<!-- JavaScript for Isotope layout and quicksearch -->
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/3.1.8/imagesloaded.pkgd.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.isotope/2.0.0/isotope.pkgd.min.js"></script>
<script>
  $(function() {
    // quick search regex
    var qsRegex;

    // init Isotope
    var $container = $('.isotope-container');

    $container.imagesLoaded(function() {
      $container.isotope({
        itemSelector: '.isotope-item',
        layoutMode: 'masonry',
        filter: function() {
          return qsRegex ? $(this).text().match( qsRegex ) : true;
        }
      })
    });

    // use value of search field to filter
    var $quicksearch = $('#quicksearch').keyup( debounce( function() {
      qsRegex = new RegExp( $quicksearch.val(), 'gi' );
      $container.isotope();
    }, 200 ) );

  });

  // debounce so filtering doesn't happen every millisecond
  function debounce( fn, threshold ) {
    var timeout;
    return function debounced() {
      if ( timeout ) {
        clearTimeout( timeout );
      }
      function delayed() {
        fn();
        timeout = null;
      }
      timeout = setTimeout( delayed, threshold || 100 );
    }
  }
</script>

<!-- End responsive, Isotope-based layout example -->

app/views/ingredients/new.html.erb
<!-- Validation failure messages -->

<% if @ingredient.errors.any? %>
  <% @ingredient.errors.full_messages.each do |message| %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= message %>
    </div>
  <% end %>
<% end %>

<!-- Responsive panel example -->

<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Add Ingredient</h3>
      </div>
      <div class="panel-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

<!-- End responsive panel example -->

app/views/ingredients/show.html.erb
<!-- Responsive panel example-->

<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Ingredient #<%= @ingredient.id %></h3>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-md-12">
            <dl class="dl-horizontal">
              <dt>Name</dt>
              <dd><%= @ingredient.name %></dd>

              <dt>Category</dt>
              <dd><%= @ingredient.category %></dd>

              <dt>Price per unit</dt>
              <dd><%= @ingredient.price_per_unit %></dd>

              <dt>Unit</dt>
              <dd><%= @ingredient.unit %></dd>

            </dl>
            <div class="btn-group btn-group-justified">
              <%= link_to ingredients_url, :class => "btn btn-primary" do %>
                <i class="fa fa-chevron-left"></i>
              <% end %>
              <%= link_to edit_ingredient_url(@ingredient.id), :class => "btn btn-warning" do %>
                <i class="fa fa-edit"></i>
              <% end %>
              <%= link_to ingredient_url(@ingredient.id), :method => "delete", :data => { :confirm => "Do you really want to delete this ingredient?" }, :class => "btn btn-danger" do %>
                <i class="fa fa-trash-o"></i>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- End responsive panel example -->