config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "recipes#index"

  get '/users/new',      :controller => 'users', :action => 'new',    :as => 'new_user'
  post '/users',         :controller => 'users', :action => 'create', :as => 'users'

  get '/users',          :controller => 'users', :action => 'index'
  get '/users/:id',      :controller => 'users', :action => 'show',   :as => 'user'

  get '/users/:id/edit', :controller => 'users', :action => 'edit',   :as => 'edit_user'
  patch '/users/:id',    :controller => 'users', :action => 'update'

  delete '/users/:id',   :controller => 'users', :action => 'destroy'

  get '/ingredients/new',      :controller => 'ingredients', :action => 'new',    :as => 'new_ingredient'
  post '/ingredients',         :controller => 'ingredients', :action => 'create', :as => 'ingredients'

  get '/ingredients',          :controller => 'ingredients', :action => 'index'
  get '/ingredients/:id',      :controller => 'ingredients', :action => 'show',   :as => 'ingredient'

  get '/ingredients/:id/edit', :controller => 'ingredients', :action => 'edit',   :as => 'edit_ingredient'
  patch '/ingredients/:id',    :controller => 'ingredients', :action => 'update'

  delete '/ingredients/:id',   :controller => 'ingredients', :action => 'destroy'

  get '/recipe_ingredients/new',      :controller => 'recipe_ingredients', :action => 'new',    :as => 'new_recipe_ingredient'
  post '/recipe_ingredients',         :controller => 'recipe_ingredients', :action => 'create', :as => 'recipe_ingredients'

  get '/recipe_ingredients',          :controller => 'recipe_ingredients', :action => 'index'
  get '/recipe_ingredients/:id',      :controller => 'recipe_ingredients', :action => 'show',   :as => 'recipe_ingredient'

  get '/recipe_ingredients/:id/edit', :controller => 'recipe_ingredients', :action => 'edit',   :as => 'edit_recipe_ingredient'
  patch '/recipe_ingredients/:id',    :controller => 'recipe_ingredients', :action => 'update'

  delete '/recipe_ingredients/:id',   :controller => 'recipe_ingredients', :action => 'destroy'

  get '/recipes/new',      :controller => 'recipes', :action => 'new',    :as => 'new_recipe'
  post '/recipes',         :controller => 'recipes', :action => 'create', :as => 'recipes'

  get '/recipes',          :controller => 'recipes', :action => 'index'
  get '/recipes/:id',      :controller => 'recipes', :action => 'show',   :as => 'recipe'

  get '/recipes/:id/edit', :controller => 'recipes', :action => 'edit',   :as => 'edit_recipe'
  patch '/recipes/:id',    :controller => 'recipes', :action => 'update'

  delete '/recipes/:id',   :controller => 'recipes', :action => 'destroy'

  get '/meals/new',      :controller => 'meals', :action => 'new',    :as => 'new_meal'
  post '/meals',         :controller => 'meals', :action => 'create', :as => 'meals'

  get '/meals',          :controller => 'meals', :action => 'index'
  get '/meals/:id',      :controller => 'meals', :action => 'show',   :as => 'meal'

  get '/meals/:id/edit', :controller => 'meals', :action => 'edit',   :as => 'edit_meal'
  patch '/meals/:id',    :controller => 'meals', :action => 'update'

  delete '/meals/:id',   :controller => 'meals', :action => 'destroy'

end

app/models/meal.rb
class Meal < ActiveRecord::Base
  def user
    User.find(self.user_id)
  end

  def recipe
    Recipe.find(self.recipe_id)
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  def index
    @meals = Meal.all
  end

  def show
    @meal = Meal.find(params[:id])
  end

  def new
    @meal = Meal.new
  end

  def create
    @meal = Meal.new(meal_params)

    if @meal.save
      redirect_to meals_url, :notice => "Meal created successfully."
    else
      render 'new'
    end
  end

  def edit
    @meal = Meal.find(params[:id])
  end

  def update
    @meal = Meal.find(params[:id])
    @meal.update_attributes(meal_params)

    if @meal.save
      redirect_to meal_url(@meal.id), :notice => "Meal updated successfully."
    else
      render 'edit'
    end
  end

  def destroy
    @meal = Meal.find(params[:id])

    @meal.destroy

    redirect_to meals_url, :notice => "Meal deleted."
  end

  def meal_params
    params.require(:meal).permit(:user_id, :recipe_id)
  end
end

app/views/meals/_form.html.erb
<%= form_for(@meal, html: {class: 'form-horizontal'}) do |f| %>
  <div class="form-group">
    <%= f.label :user_id, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.collection_select :user_id, User.all, :id, :username %>
    </div>
  </div>

  <!-- Label and input for recipe_id -->
  <div class="form-group">
    <%= f.label :recipe_id, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.collection_select :recipe_id, Recipe.all, :id, :name %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: 'btn btn-default' %>
      or
      <a href="/meals">Cancel</a>
    </div>
  </div>
<% end %>

app/views/meals/edit.html.erb
<!-- Validation failure messages -->

<% if @meal.errors.any? %>
  <% @meal.errors.full_messages.each do |message| %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= message %>
    </div>
  <% end %>
<% end %>

<!-- Responsive panel example -->

<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Edit Meal #<%= @meal.id %></h3>
      </div>
      <div class="panel-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>


<!-- End responsive panel example -->

app/views/meals/index.html.erb
<div class="page-header">
  <h1>
    Meals
    <%= link_to new_meal_url, :class => "btn btn-lg btn-success" do %>
      <i class="fa fa-plus"></i>
    <% end  %>
  </h1>
</div>

<!-- Responsive, Isotope-based layout example -->

<div class="row">
  <div class="col-xs-12">
    <input type="text" id="quicksearch" placeholder="Search Meals (start typing)" class="form-control">
  </div>
</div>

<hr>

<div class="row isotope-container">
<% @meals.each do |meal| %>
  <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 isotope-item">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Meal #<%= meal.id %></h3>
      </div>
      <div class="panel-body">
        <dl>
          <dt>User</dt>
          <dd><%= meal.user.username %></dd>

          <dt>Recipe</dt>
          <dd><%= meal.recipe.name %></dd>

        </dl>
        <div class="btn-group btn-group-justified">
          <%= link_to meal_url(meal), :class => "btn btn-primary" do %>
            <i class="fa fa-search-plus"></i>
          <% end %>
          <%= link_to edit_meal_url(meal), :class => "btn btn-warning" do %>
            <i class="fa fa-edit"></i>
          <% end %>
          <%= link_to meal_url(meal), :method => "delete", :data => { :confirm => "Do you really want to delete this meal?" }, :class => "btn btn-danger" do %>
            <i class="fa fa-trash-o"></i>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>
</div>

<!-- JavaScript for Isotope layout and quicksearch -->
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/3.1.8/imagesloaded.pkgd.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.isotope/2.0.0/isotope.pkgd.min.js"></script>
<script>
  $(function() {
    // quick search regex
    var qsRegex;

    // init Isotope
    var $container = $('.isotope-container');

    $container.imagesLoaded(function() {
      $container.isotope({
        itemSelector: '.isotope-item',
        layoutMode: 'masonry',
        filter: function() {
          return qsRegex ? $(this).text().match( qsRegex ) : true;
        }
      })
    });

    // use value of search field to filter
    var $quicksearch = $('#quicksearch').keyup( debounce( function() {
      qsRegex = new RegExp( $quicksearch.val(), 'gi' );
      $container.isotope();
    }, 200 ) );

  });

  // debounce so filtering doesn't happen every millisecond
  function debounce( fn, threshold ) {
    var timeout;
    return function debounced() {
      if ( timeout ) {
        clearTimeout( timeout );
      }
      function delayed() {
        fn();
        timeout = null;
      }
      timeout = setTimeout( delayed, threshold || 100 );
    }
  }
</script>

<!-- End responsive, Isotope-based layout example -->

app/views/meals/new.html.erb
<!-- Validation failure messages -->

<% if @meal.errors.any? %>
  <% @meal.errors.full_messages.each do |message| %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= message %>
    </div>
  <% end %>
<% end %>

<!-- Responsive panel example -->

<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Add Meal</h3>
      </div>
      <div class="panel-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

<!-- End responsive panel example -->

app/views/meals/show.html.erb
<!-- Responsive panel example-->

<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Meal #<%= @meal.id %></h3>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-md-12">
            <dl class="dl-horizontal">
              <dt>User</dt>
              <dd><%= @meal.user_id %></dd>

              <dt>Recipe</dt>
              <dd><%= @meal.recipe_id %></dd>

            </dl>
            <div class="btn-group btn-group-justified">
              <%= link_to meals_url, :class => "btn btn-primary" do %>
                <i class="fa fa-chevron-left"></i>
              <% end %>
              <%= link_to edit_meal_url(@meal.id), :class => "btn btn-warning" do %>
                <i class="fa fa-edit"></i>
              <% end %>
              <%= link_to meal_url(@meal.id), :method => "delete", :data => { :confirm => "Do you really want to delete this meal?" }, :class => "btn btn-danger" do %>
                <i class="fa fa-trash-o"></i>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- End responsive panel example -->